---
- name: Install and configure Nginx on AlmaLinux servers
  hosts: almalinux_servers
  become: yes
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present
        
    - name: Start and enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
        
    - name: Create custom Nginx configuration
      copy:
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';

              access_log /var/log/nginx/access.log main;

              sendfile on;
              tcp_nopush on;
              tcp_nodelay on;
              keepalive_timeout 65;
              types_hash_max_size 2048;

              include /etc/nginx/mime.types;
              default_type application/octet-stream;

              server {
                  listen 80 default_server;
                  listen [::]:80 default_server;
                  server_name _;
                  root /usr/share/nginx/html;

                  location / {
                      index index.html index.htm;
                  }

                  error_page 404 /404.html;
                  location = /404.html {
                  }

                  error_page 500 502 503 504 /50x.html;
                  location = /50x.html {
                  }
              }
          }
        dest: /etc/nginx/nginx.conf
        backup: yes
      notify: restart nginx
        
    - name: Create custom index page
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Ansible Managed Server</title>
          </head>
          <body>
              <h1>Hello from {{ inventory_hostname }}!</h1>
              <p>This server is managed by Ansible</p>
              <p>Server IP: {{ ansible_default_ipv4.address }}</p>
          </body>
          </html>
        dest: /usr/share/nginx/html/index.html
        
    - name: Open firewall for HTTP
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
        
  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
