---
- name: Install Java 11 on AlmaLinux servers
  hosts: almalinux_servers
  become: yes
  tasks:
    - name: Install OpenJDK 11
      dnf:
        name: java-11-openjdk
        state: present
      
    - name: Install OpenJDK 11 Development Kit
      dnf:
        name: java-11-openjdk-devel
        state: present
        
    - name: Verify Java installation
      command: java -version
      register: java_version
      
    - name: Display Java version
      debug:
        var: java_version.stderr
